coreWebApplication/coreWebApplication/Models/Customer.cs
namespace coreWebApplication.Models
{
    public class Customer
    {
        public int Id { get; set; }
        public string? Name { get; set; }
        public double Amount { get; set; }
    }
}

coreWebApplication/coreWebApplication/Models/ErrorViewModel.cs
namespace coreWebApplication.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

coreWebApplication/coreWebApplication/Controllers/CustomerController.cs
using coreWebApplication.Models;
using Microsoft.AspNetCore.Mvc;


namespace coreWebApplication.Controllers
{
    public class CustomerController : Controller
    {
        public static List<Customer> customers = new List<Customer>()
        {
            new Customer() {Id = 101, Name = "John", Amount = 12000},
            new Customer() {Id = 102, Name = "John", Amount = 12000},
        };

        public IActionResult Index()
        {
            ViewBag.Message = "Customer Management System";
            ViewBag.CustomerCount = customers.Count();
            ViewBag.CustomerList = customers;
            return View();
        }
        public IActionResult Details()
        {        
            return View();
        }
//        [Route("~/")]
        [Route("/sample/message")]

        public IActionResult Message()
        {
            return View();
        }

    }
}

coreWebApplication/coreWebApplication/Controllers/DemoController.cs
using coreWebApplication.Models;
using Microsoft.AspNetCore.Mvc;

public class DemoController : Controller
{
    public static List<Customer> customers = new List<Customer>()
    {
        new Customer() {Id = 101, Name = "John", Amount = 12000},
        new Customer() {Id = 102, Name = "John", Amount = 12000},
    };

    public IActionResult Index()
    {
        ViewBag.Message = "Customer Management System";
        ViewBag.CustomerCount = customers.Count();
        ViewBag.CustomerList = customers;
        return View();
    }
    public IActionResult Details()
    {
        ViewData["Message"] = "Customer Management System";
        ViewData["CustomerCount"] = customers.Count();
        ViewData["CustomerList"] = customers;
        return View();
    }

    public IActionResult Method1()
    {
        TempData["Message"] = "Customer Management System";
        TempData["CustomerCount"] = customers.Count();
        TempData["CustomerList"] = customers;
        return View();
    }
    public IActionResult Method2()
    {
        if (TempData["Message"] == null)
            return RedirectToAction("Index");
        TempData["Message"] = TempData["Message"].ToString();
        return View();
    }

    public IActionResult Login()
    {
        HttpContext.Session.SetString("username", "Henri");
        return RedirectToAction("Success");
    }
    public IActionResult Success()
    {
        ViewBag.Username = HttpContext.Session.GetString("username");
        return View();
    }
    public IActionResult Logout()
    {
        HttpContext.Session.Remove("Username");
        return RedirectToAction("Index");
    }

    //Request Url: http://localhost:5219/Demo/QueryTest
    //Request Url: http://localhost:5219/Demo/QueryTest?name=Henri


    public IActionResult QueryTest()
    {
        string name = "King Kochhar";
        if (!String.IsNullOrEmpty(HttpContext.Request.Query[name]))
            name = HttpContext.Request.Query["name"];
        ViewBag.Name = name;
        return View();
    }



}

coreWebApplication/coreWebApplication/Controllers/HomeController.cs
using System.Diagnostics;
using coreWebApplication.Models;
using Microsoft.AspNetCore.Mvc;

namespace coreWebApplication.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public ViewResult Message()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

coreWebApplication/coreWebApplication/Views/Customer/Details.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Details";
}

<h1>Details</h1>
<h2>Welcome to the Home Page!</h2>
<p>Unique Index view content</p>

coreWebApplication/coreWebApplication/Views/Customer/Details1.cshtml
@{
    ViewData["Title"] = "Details1";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details1</h1>

<h2>Welcome to the Home Page!</h2>
<p>This content is unique to the Index view.</p>

coreWebApplication/coreWebApplication/Views/Customer/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<h3>@ViewBag.Message</h3>
<p>There are @ViewBag.CustomerCount customer added to the list.</p>

<ul>
    @foreach(var item in ViewBag.CustomerList) 
    {
        <li>@item.Id - @item.Name - @item.Amount</li>
    }
</ul>

<hr/>

@Html.ActionLink("Details Page", "Details", "Customer")
<br/> 
<a asp-controller="Customer" asp-action="Message">Message</a>

coreWebApplication/coreWebApplication/Views/Customer/Message.cshtml
@{
    ViewData["Title"] = "Message";
}

<h1>Message</h1>


<h2>MessageView(s)</h2>

coreWebApplication/coreWebApplication/Views/Demo/Details.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <h2>@ViewData["Message"]</h2>
    <p>There are @ViewData["CustomerCount"] customers added to the list.</p>
    <table>
        <thead>
            <tr>
                <th>Customer Id</th>
                <th>Customer Name</th>
                <th>Customer Amount</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in ViewData["CustomerList"] as List<Customer>)
            {
                <tr>
                    <td>@item.Id</td>
                    <td>@item.Name</td>
                    <td>@item.Amount</td>
                </tr>

            }
        </tbody>
    </table>
</body>
</html>

coreWebApplication/coreWebApplication/Views/Demo/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <h2>@ViewBag.Message</h2>
    <p>There are @ViewBag.CustomerCount added to the list.</p>
    <table>
        <thead>
            <tr>
                <th>Customer Id</th>
                <th>Customer Name</th>
                <th>Customer Amount</th>
            </tr>
        </thead>
    <tbody>
        @foreach (var item in ViewBag.CustomerList) 
        {
        <tr>
            <td>@item.Id</td>
            <td>@item.Name</td>
            <td>@item.Amount</td>
        </tr>

        }
    </tbody>
    </table>
</body>
</html>

coreWebApplication/coreWebApplication/Views/Demo/Method1.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Method1</title>
</head>
<body>
    <h2>@TempData["Message"]</h2>
    <p>There are @TempData["CustomerCount"] customers added to the list.</p>
    <table>
        <thead>
            <tr>
                <th>Customer Id</th>
                <th>Customer Name</th>
                <th>Customer Amount</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in TempData["CustomerList"] as List<Customer>)
            {
                <tr>
                    <td>@item.Id</td>
                    <td>@item.Name</td>
                    <td>@item.Amount</td>
                </tr>

            }
        </tbody>
    </table>

    @{
        TempData.Keep("Message");
    }

    <a asp-controller="Demo" asp-action="Method2">Go to Method2</a>
</body>
</html>

coreWebApplication/coreWebApplication/Views/Demo/Method2.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Method2</title>
</head>
<body>
    <h2>@TempData["Message"]</h2>
</body>
</html>

coreWebApplication/coreWebApplication/Views/Demo/QueryTest.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>QueryTest</title>
</head>
<body>
    <h2>@ViewBag.Name</h2>
</body>
</html>

coreWebApplication/coreWebApplication/Views/Demo/Success.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Success</title>
</head>
<body>
    <h2>Welcome @ViewBag.Username</h2>
    <a asp-controller="Demo" asp-action="Logout">Logout</a>
</body>
</html>